// DICTIONNAIRE COMPLET : mots/synonymes → thématiques et intentions

const KEYWORD_MAP: Record<string, { theme?: string; intention?: string }> = {

  // ═══════════════════════════════════════════════════════════
  // MUSIQUE
  // ═══════════════════════════════════════════════════════════
  'musique': { theme: 'musique' },
  'musicien': { theme: 'musique' },
  'musicienne': { theme: 'musique' },
  'chanteur': { theme: 'musique' },
  'chanteuse': { theme: 'musique' },
  'chanter': { theme: 'musique' },
  'guitare': { theme: 'musique' },
  'guitariste': { theme: 'musique' },
  'piano': { theme: 'musique' },
  'pianiste': { theme: 'musique' },
  'batterie': { theme: 'musique' },
  'batteur': { theme: 'musique' },
  'violon': { theme: 'musique' },
  'violoniste': { theme: 'musique' },
  'saxophone': { theme: 'musique' },
  'trompette': { theme: 'musique' },
  'flûte': { theme: 'musique' },
  'basse': { theme: 'musique' },
  'bassiste': { theme: 'musique' },
  'concert': { theme: 'musique' },
  'concerts': { theme: 'musique' },
  'festival': { theme: 'musique' },
  'groupe': { theme: 'musique' },
  'band': { theme: 'musique' },
  'jazz': { theme: 'musique' },
  'rock': { theme: 'musique' },
  'pop': { theme: 'musique' },
  'classique': { theme: 'musique' },
  'rap': { theme: 'musique' },
  'hiphop': { theme: 'musique' },
  'hip-hop': { theme: 'musique' },
  'electro': { theme: 'musique' },
  'techno': { theme: 'musique' },
  'house': { theme: 'musique' },
  'reggae': { theme: 'musique' },
  'metal': { theme: 'musique' },
  'punk': { theme: 'musique' },
  'blues': { theme: 'musique' },
  'soul': { theme: 'musique' },
  'funk': { theme: 'musique' },
  'rnb': { theme: 'musique' },
  'r&b': { theme: 'musique' },
  'dj': { theme: 'musique' },
  'deejay': { theme: 'musique' },
  'platines': { theme: 'musique' },
  'mix': { theme: 'musique' },
  'remix': { theme: 'musique' },
  'composer': { theme: 'musique' },
  'compositeur': { theme: 'musique' },
  'composition': { theme: 'musique' },
  'mélodie': { theme: 'musique' },
  'chanson': { theme: 'musique' },
  'chansons': { theme: 'musique' },
  'karaoké': { theme: 'musique' },
  'chorale': { theme: 'musique' },
  'orchestre': { theme: 'musique' },
  'conservatoire': { theme: 'musique' },
  'solfège': { theme: 'musique' },

  // ═══════════════════════════════════════════════════════════
  // ART / CRÉATION
  // ═══════════════════════════════════════════════════════════
  'art': { theme: 'art' },
  'arts': { theme: 'art' },
  'artiste': { theme: 'art' },
  'artistique': { theme: 'art' },
  'peintre': { theme: 'art' },
  'peinture': { theme: 'art' },
  'peindre': { theme: 'art' },
  'tableau': { theme: 'art' },
  'tableaux': { theme: 'art' },
  'toile': { theme: 'art' },
  'dessin': { theme: 'art' },
  'dessiner': { theme: 'art' },
  'dessinateur': { theme: 'art' },
  'croquis': { theme: 'art' },
  'esquisse': { theme: 'art' },
  'sculpture': { theme: 'art' },
  'sculpteur': { theme: 'art' },
  'sculter': { theme: 'art' },
  'poterie': { theme: 'art' },
  'céramique': { theme: 'art' },
  'créatif': { theme: 'art' },
  'créative': { theme: 'art' },
  'créativité': { theme: 'art' },
  'création': { theme: 'art' },
  'créer': { theme: 'art' },
  'illustration': { theme: 'art' },
  'illustrateur': { theme: 'art' },
  'illustratrice': { theme: 'art' },
  'graphiste': { theme: 'art' },
  'graphisme': { theme: 'art' },
  'design': { theme: 'art' },
  'designer': { theme: 'art' },
  'ux': { theme: 'art' },
  'ui': { theme: 'art' },
  'webdesign': { theme: 'art' },
  'logo': { theme: 'art' },
  'affiche': { theme: 'art' },
  'aquarelle': { theme: 'art' },
  'acrylique': { theme: 'art' },
  'huile': { theme: 'art' },
  'pastel': { theme: 'art' },
  'fusain': { theme: 'art' },
  'gravure': { theme: 'art' },
  'collage': { theme: 'art' },
  'street-art': { theme: 'art' },
  'streetart': { theme: 'art' },
  'graffiti': { theme: 'art' },
  'tag': { theme: 'art' },
  'fresque': { theme: 'art' },
  'galerie': { theme: 'art' },
  'exposition': { theme: 'art' },
  'expo': { theme: 'art' },
  'musée': { theme: 'art' },
  'vernissage': { theme: 'art' },
  'atelier': { theme: 'art' },
  'beaux-arts': { theme: 'art' },

  // ═══════════════════════════════════════════════════════════
  // PHOTOGRAPHIE
  // ═══════════════════════════════════════════════════════════
  'photo': { theme: 'photo' },
  'photos': { theme: 'photo' },
  'photographie': { theme: 'photo' },
  'photographe': { theme: 'photo' },
  'photographier': { theme: 'photo' },
  'appareil': { theme: 'photo' },
  'reflex': { theme: 'photo' },
  'objectif': { theme: 'photo' },
  'portrait': { theme: 'photo' },
  'portraits': { theme: 'photo' },
  'paysage': { theme: 'photo' },
  'paysages': { theme: 'photo' },
  'macro': { theme: 'photo' },
  'lightroom': { theme: 'photo' },
  'photoshop': { theme: 'photo' },
  'retouche': { theme: 'photo' },
  'shooting': { theme: 'photo' },
  'studio': { theme: 'photo' },
  'argentique': { theme: 'photo' },
  'numérique': { theme: 'photo' },
  'instagram': { theme: 'photo' },
  'instagrameur': { theme: 'photo' },

  // ═══════════════════════════════════════════════════════════
  // CINÉMA / SÉRIES
  // ═══════════════════════════════════════════════════════════
  'cinéma': { theme: 'cinema' },
  'cinema': { theme: 'cinema' },
  'ciné': { theme: 'cinema' },
  'film': { theme: 'cinema' },
  'films': { theme: 'cinema' },
  'cinéphile': { theme: 'cinema' },
  'série': { theme: 'cinema' },
  'séries': { theme: 'cinema' },
  'series': { theme: 'cinema' },
  'netflix': { theme: 'cinema' },
  'réalisateur': { theme: 'cinema' },
  'réalisatrice': { theme: 'cinema' },
  'réalisation': { theme: 'cinema' },
  'scénario': { theme: 'cinema' },
  'scénariste': { theme: 'cinema' },
  'acteur': { theme: 'cinema' },
  'actrice': { theme: 'cinema' },
  'comédien': { theme: 'cinema' },
  'comédienne': { theme: 'cinema' },
  'théâtre': { theme: 'cinema' },
  'theatre': { theme: 'cinema' },
  'comédie': { theme: 'cinema' },
  'drame': { theme: 'cinema' },
  'thriller': { theme: 'cinema' },
  'horreur': { theme: 'cinema' },
  'science-fiction': { theme: 'cinema' },
  'sf': { theme: 'cinema' },
  'fantastique': { theme: 'cinema' },
  'documentaire': { theme: 'cinema' },
  'animation': { theme: 'cinema' },
  'anime': { theme: 'cinema' },
  'manga': { theme: 'cinema' },
  'court-métrage': { theme: 'cinema' },
  'tournage': { theme: 'cinema' },
  'montage': { theme: 'cinema' },
  'vidéo': { theme: 'cinema' },
  'youtube': { theme: 'cinema' },
  'youtuber': { theme: 'cinema' },
  'youtubeur': { theme: 'cinema' },
  'streaming': { theme: 'cinema' },
  'blockbuster': { theme: 'cinema' },

  // ═══════════════════════════════════════════════════════════
  // LITTÉRATURE / ÉCRITURE
  // ═══════════════════════════════════════════════════════════
  'livre': { theme: 'litterature' },
  'livres': { theme: 'litterature' },
  'lecture': { theme: 'litterature' },
  'lire': { theme: 'litterature' },
  'lecteur': { theme: 'litterature' },
  'lectrice': { theme: 'litterature' },
  'littérature': { theme: 'litterature' },
  'litterature': { theme: 'litterature' },
  'roman': { theme: 'litterature' },
  'romans': { theme: 'litterature' },
  'nouvelle': { theme: 'litterature' },
  'nouvelles': { theme: 'litterature' },
  'poésie': { theme: 'litterature' },
  'poème': { theme: 'litterature' },
  'poète': { theme: 'litterature' },
  'écrivain': { theme: 'litterature' },
  'écrivaine': { theme: 'litterature' },
  'auteur': { theme: 'litterature' },
  'autrice': { theme: 'litterature' },
  'écrire': { theme: 'litterature' },
  'écriture': { theme: 'litterature' },
  'rédaction': { theme: 'litterature' },
  'rédacteur': { theme: 'litterature' },
  'journaliste': { theme: 'litterature' },
  'journalisme': { theme: 'litterature' },
  'blog': { theme: 'litterature' },
  'blogueur': { theme: 'litterature' },
  'blogueuse': { theme: 'litterature' },
  'essai': { theme: 'litterature' },
  'biographie': { theme: 'litterature' },
  'autobiographie': { theme: 'litterature' },
  'bd': { theme: 'litterature' },
  'bande-dessinée': { theme: 'litterature' },
  'comics': { theme: 'litterature' },
  'bibliothèque': { theme: 'litterature' },
  'librairie': { theme: 'litterature' },
  'bouquin': { theme: 'litterature' },
  'bouquiner': { theme: 'litterature' },

  // ═══════════════════════════════════════════════════════════
  // SCIENCE / TECH
  // ═══════════════════════════════════════════════════════════
  'science': { theme: 'science' },
  'sciences': { theme: 'science' },
  'scientifique': { theme: 'science' },
  'recherche': { theme: 'science' },
  'chercheur': { theme: 'science' },
  'chercheuse': { theme: 'science' },
  'labo': { theme: 'science' },
  'laboratoire': { theme: 'science' },
  'physique': { theme: 'science' },
  'chimie': { theme: 'science' },
  'biologie': { theme: 'science' },
  'mathématiques': { theme: 'science' },
  'maths': { theme: 'science' },
  'astronomie': { theme: 'science' },
  'espace': { theme: 'science' },
  'tech': { theme: 'science' },
  'technologie': { theme: 'science' },
  'technologies': { theme: 'science' },
  'informatique': { theme: 'science' },
  'développeur': { theme: 'science' },
  'développeuse': { theme: 'science' },
  'dev': { theme: 'science' },
  'programmeur': { theme: 'science' },
  'programmeuse': { theme: 'science' },
  'programmer': { theme: 'science' },
  'programmation': { theme: 'science' },
  'code': { theme: 'science' },
  'coder': { theme: 'science' },
  'codeur': { theme: 'science' },
  'coding': { theme: 'science' },
  'software': { theme: 'science' },
  'hardware': { theme: 'science' },
  'web': { theme: 'science' },
  'internet': { theme: 'science' },
  'startup': { theme: 'science' },
  'startups': { theme: 'science' },
  'entrepreneur': { theme: 'science' },
  'geek': { theme: 'science' },
  'nerd': { theme: 'science' },
  'ia': { theme: 'science' },
  'intelligence artificielle': { theme: 'science' },
  'machine learning': { theme: 'science' },
  'data': { theme: 'science' },
  'données': { theme: 'science' },
  'blockchain': { theme: 'science' },
  'crypto': { theme: 'science' },
  'robot': { theme: 'science' },
  'robotique': { theme: 'science' },
  'ingénieur': { theme: 'science' },
  'ingénieure': { theme: 'science' },
  'électronique': { theme: 'science' },

  // ═══════════════════════════════════════════════════════════
  // POLITIQUE / SOCIÉTÉ
  // ═══════════════════════════════════════════════════════════
  'politique': { theme: 'politique' },
  'politiques': { theme: 'politique' },
  'politisé': { theme: 'politique' },
  'débat': { theme: 'politique' },
  'débats': { theme: 'politique' },
  'débattre': { theme: 'politique' },
  'militant': { theme: 'politique' },
  'militante': { theme: 'politique' },
  'militantisme': { theme: 'politique' },
  'engagement': { theme: 'politique' },
  'engagé': { theme: 'politique' },
  'engagée': { theme: 'politique' },
  'activiste': { theme: 'politique' },
  'activisme': { theme: 'politique' },
  'société': { theme: 'politique' },
  'social': { theme: 'politique' },
  'sociale': { theme: 'politique' },
  'sociaux': { theme: 'politique' },
  'citoyen': { theme: 'politique' },
  'citoyenne': { theme: 'politique' },
  'citoyenneté': { theme: 'politique' },
  'démocratie': { theme: 'politique' },
  'économie': { theme: 'politique' },
  'économique': { theme: 'politique' },
  'géopolitique': { theme: 'politique' },
  'histoire': { theme: 'politique' },
  'historien': { theme: 'politique' },
  'actualité': { theme: 'politique' },
  'actualités': { theme: 'politique' },
  'news': { theme: 'politique' },
  'féminisme': { theme: 'politique' },
  'féministe': { theme: 'politique' },
  'égalité': { theme: 'politique' },
  'droits': { theme: 'politique' },
  'justice': { theme: 'politique' },
  'humanitaire': { theme: 'politique' },
  'association': { theme: 'politique' },
  'bénévole': { theme: 'politique' },
  'bénévolat': { theme: 'politique' },
  'ong': { theme: 'politique' },
  'solidarité': { theme: 'politique' },
  'solidaire': { theme: 'politique' },

  // ═══════════════════════════════════════════════════════════
  // PHILOSOPHIE
  // ═══════════════════════════════════════════════════════════
  'philosophie': { theme: 'philosophie' },
  'philo': { theme: 'philosophie' },
  'philosophe': { theme: 'philosophie' },
  'philosopher': { theme: 'philosophie' },
  'philosophique': { theme: 'philosophie' },
  'penseur': { theme: 'philosophie' },
  'penser': { theme: 'philosophie' },
  'pensée': { theme: 'philosophie' },
  'réflexion': { theme: 'philosophie' },
  'réfléchir': { theme: 'philosophie' },
  'sagesse': { theme: 'philosophie' },
  'existentiel': { theme: 'philosophie' },
  'existentialisme': { theme: 'philosophie' },
  'métaphysique': { theme: 'philosophie' },
  'éthique': { theme: 'philosophie' },
  'morale': { theme: 'philosophie' },
  'sens': { theme: 'philosophie' },
  'questionnement': { theme: 'philosophie' },

  // ═══════════════════════════════════════════════════════════
  // VOYAGE
  // ═══════════════════════════════════════════════════════════
  'voyage': { theme: 'voyage' },
  'voyages': { theme: 'voyage' },
  'voyager': { theme: 'voyage' },
  'voyageur': { theme: 'voyage' },
  'voyageuse': { theme: 'voyage' },
  'travel': { theme: 'voyage' },
  'traveler': { theme: 'voyage' },
  'nomade': { theme: 'voyage' },
  'digital nomad': { theme: 'voyage' },
  'aventure': { theme: 'voyage' },
  'aventurier': { theme: 'voyage' },
  'aventurière': { theme: 'voyage' },
  'exploration': { theme: 'voyage' },
  'explorer': { theme: 'voyage' },
  'explorateur': { theme: 'voyage' },
  'découverte': { theme: 'voyage' },
  'découvrir': { theme: 'voyage' },
  'backpack': { theme: 'voyage' },
  'backpacker': { theme: 'voyage' },
  'sac à dos': { theme: 'voyage' },
  'roadtrip': { theme: 'voyage' },
  'road trip': { theme: 'voyage' },
  'tour du monde': { theme: 'voyage' },
  'expat': { theme: 'voyage' },
  'expatrié': { theme: 'voyage' },
  'expatriée': { theme: 'voyage' },
  'étranger': { theme: 'voyage' },
  'international': { theme: 'voyage' },
  'interculturel': { theme: 'voyage' },
  'culture': { theme: 'voyage' },
  'cultures': { theme: 'voyage' },

  // ═══════════════════════════════════════════════════════════
  // SPORT / FITNESS
  // ═══════════════════════════════════════════════════════════
  'sport': { theme: 'sport' },
  'sports': { theme: 'sport' },
  'sportif': { theme: 'sport' },
  'sportive': { theme: 'sport' },
  'athlète': { theme: 'sport' },
  'fitness': { theme: 'sport' },
  'musculation': { theme: 'sport' },
  'muscu': { theme: 'sport' },
  'gym': { theme: 'sport' },
  'salle': { theme: 'sport' },
  'crossfit': { theme: 'sport' },
  'yoga': { theme: 'sport' },
  'pilates': { theme: 'sport' },
  'stretching': { theme: 'sport' },
  'running': { theme: 'sport' },
  'courir': { theme: 'sport' },
  'course': { theme: 'sport' },
  'jogging': { theme: 'sport' },
  'marathon': { theme: 'sport' },
  'trail': { theme: 'sport' },
  'vélo': { theme: 'sport' },
  'cyclisme': { theme: 'sport' },
  'vtt': { theme: 'sport' },
  'cycliste': { theme: 'sport' },
  'natation': { theme: 'sport' },
  'nager': { theme: 'sport' },
  'piscine': { theme: 'sport' },
  'plongée': { theme: 'sport' },
  'surf': { theme: 'sport' },
  'surfeur': { theme: 'sport' },
  'kitesurf': { theme: 'sport' },
  'voile': { theme: 'sport' },
  'rando': { theme: 'sport' },
  'randonnée': { theme: 'sport' },
  'randonneur': { theme: 'sport' },
  'marche': { theme: 'sport' },
  'montagne': { theme: 'sport' },
  'alpinisme': { theme: 'sport' },
  'escalade': { theme: 'sport' },
  'grimpe': { theme: 'sport' },
  'grimper': { theme: 'sport' },
  'ski': { theme: 'sport' },
  'snowboard': { theme: 'sport' },
  'foot': { theme: 'sport' },
  'football': { theme: 'sport' },
  'rugby': { theme: 'sport' },
  'tennis': { theme: 'sport' },
  'basket': { theme: 'sport' },
  'basketball': { theme: 'sport' },
  'volley': { theme: 'sport' },
  'handball': { theme: 'sport' },
  'boxe': { theme: 'sport' },
  'boxeur': { theme: 'sport' },
  'arts martiaux': { theme: 'sport' },
  'judo': { theme: 'sport' },
  'karaté': { theme: 'sport' },
  'taekwondo': { theme: 'sport' },
  'mma': { theme: 'sport' },
  'danse': { theme: 'sport' },
  'danser': { theme: 'sport' },
  'danseur': { theme: 'sport' },
  'danseuse': { theme: 'sport' },
  'salsa': { theme: 'sport' },
  'tango': { theme: 'sport' },
  'équitation': { theme: 'sport' },
  'cheval': { theme: 'sport' },
  'golf': { theme: 'sport' },
  'paddle': { theme: 'sport' },
  'kayak': { theme: 'sport' },

  // ═══════════════════════════════════════════════════════════
  // CUISINE / GASTRONOMIE
  // ═══════════════════════════════════════════════════════════
  'cuisine': { theme: 'cuisine' },
  'cuisiner': { theme: 'cuisine' },
  'cuisinier': { theme: 'cuisine' },
  'cuisinière': { theme: 'cuisine' },
  'culinaire': { theme: 'cuisine' },
  'chef': { theme: 'cuisine' },
  'gastronomie': { theme: 'cuisine' },
  'gastronome': { theme: 'cuisine' },
  'foodie': { theme: 'cuisine' },
  'food': { theme: 'cuisine' },
  'gourmand': { theme: 'cuisine' },
  'gourmande': { theme: 'cuisine' },
  'gourmet': { theme: 'cuisine' },
  'recette': { theme: 'cuisine' },
  'recettes': { theme: 'cuisine' },
  'plat': { theme: 'cuisine' },
  'plats': { theme: 'cuisine' },
  'repas': { theme: 'cuisine' },
  'pâtisserie': { theme: 'cuisine' },
  'pâtissier': { theme: 'cuisine' },
  'boulangerie': { theme: 'cuisine' },
  'gâteau': { theme: 'cuisine' },
  'dessert': { theme: 'cuisine' },
  'vin': { theme: 'cuisine' },
  'vins': { theme: 'cuisine' },
  'oenologie': { theme: 'cuisine' },
  'sommelier': { theme: 'cuisine' },
  'dégustation': { theme: 'cuisine' },
  'resto': { theme: 'cuisine' },
  'restaurant': { theme: 'cuisine' },
  'restaurants': { theme: 'cuisine' },
  'brunch': { theme: 'cuisine' },
  'bistrot': { theme: 'cuisine' },
  'bar': { theme: 'cuisine' },
  'cocktail': { theme: 'cuisine' },
  'cocktails': { theme: 'cuisine' },
  'bière': { theme: 'cuisine' },
  'brasserie': { theme: 'cuisine' },
  'café': { theme: 'cuisine' },
  'thé': { theme: 'cuisine' },

  // ═══════════════════════════════════════════════════════════
  // ÉCOLOGIE / NATURE
  // ═══════════════════════════════════════════════════════════
  'écologie': { theme: 'ecologie' },
  'ecologie': { theme: 'ecologie' },
  'écolo': { theme: 'ecologie' },
  'écologique': { theme: 'ecologie' },
  'environnement': { theme: 'ecologie' },
  'environnemental': { theme: 'ecologie' },
  'nature': { theme: 'ecologie' },
  'naturel': { theme: 'ecologie' },
  'bio': { theme: 'ecologie' },
  'biologique': { theme: 'ecologie' },
  'vegan': { theme: 'ecologie' },
  'végane': { theme: 'ecologie' },
  'végétarien': { theme: 'ecologie' },
  'végétarienne': { theme: 'ecologie' },
  'végétal': { theme: 'ecologie' },
  'climat': { theme: 'ecologie' },
  'climatique': { theme: 'ecologie' },
  'durable': { theme: 'ecologie' },
  'durabilité': { theme: 'ecologie' },
  'zéro déchet': { theme: 'ecologie' },
  'zero waste': { theme: 'ecologie' },
  'recyclage': { theme: 'ecologie' },
  'recycler': { theme: 'ecologie' },
  'planète': { theme: 'ecologie' },
  'terre': { theme: 'ecologie' },
  'permaculture': { theme: 'ecologie' },
  'jardin': { theme: 'ecologie' },
  'jardinage': { theme: 'ecologie' },
  'potager': { theme: 'ecologie' },
  'plante': { theme: 'ecologie' },
  'plantes': { theme: 'ecologie' },
  'botanique': { theme: 'ecologie' },
  'forêt': { theme: 'ecologie' },
  'animaux': { theme: 'ecologie' },
  'animal': { theme: 'ecologie' },
  'animalier': { theme: 'ecologie' },

  // ═══════════════════════════════════════════════════════════
  // JEUX / GAMING
  // ═══════════════════════════════════════════════════════════
  'jeu': { theme: 'jeux' },
  'jeux': { theme: 'jeux' },
  'jouer': { theme: 'jeux' },
  'joueur': { theme: 'jeux' },
  'joueuse': { theme: 'jeux' },
  'gaming': { theme: 'jeux' },
  'gamer': { theme: 'jeux' },
  'gameuse': { theme: 'jeux' },
  'videogame': { theme: 'jeux' },
  'jeu vidéo': { theme: 'jeux' },
  'jeux vidéo': { theme: 'jeux' },
  'console': { theme: 'jeux' },
  'pc gamer': { theme: 'jeux' },
  'playstation': { theme: 'jeux' },
  'xbox': { theme: 'jeux' },
  'nintendo': { theme: 'jeux' },
  'switch': { theme: 'jeux' },
  'steam': { theme: 'jeux' },
  'esport': { theme: 'jeux' },
  'e-sport': { theme: 'jeux' },
  'compétitif': { theme: 'jeux' },
  'mmorpg': { theme: 'jeux' },
  'rpg': { theme: 'jeux' },
  'fps': { theme: 'jeux' },
  'stratégie': { theme: 'jeux' },
  'simulation': { theme: 'jeux' },
  'streamer': { theme: 'jeux' },
  'twitch': { theme: 'jeux' },
  'jeu de société': { theme: 'jeux' },
  'jeux de société': { theme: 'jeux' },
  'boardgame': { theme: 'jeux' },
  'échecs': { theme: 'jeux' },
  'poker': { theme: 'jeux' },
  'cartes': { theme: 'jeux' },
  'jeu de rôle': { theme: 'jeux' },
  'roleplay': { theme: 'jeux' },
  'donjons et dragons': { theme: 'jeux' },
  'd&d': { theme: 'jeux' },

  // ═══════════════════════════════════════════════════════════
  // SPIRITUALITÉ
  // ═══════════════════════════════════════════════════════════
  'spirituel': { theme: 'spiritualite' },
  'spirituelle': { theme: 'spiritualite' },
  'spiritualité': { theme: 'spiritualite' },
  'méditation': { theme: 'spiritualite' },
  'méditer': { theme: 'spiritualite' },
  'mindfulness': { theme: 'spiritualite' },
  'pleine conscience': { theme: 'spiritualite' },
  'bouddhisme': { theme: 'spiritualite' },
  'bouddhiste': { theme: 'spiritualite' },
  'zen': { theme: 'spiritualite' },
  'hindouisme': { theme: 'spiritualite' },
  'yoga spirituel': { theme: 'spiritualite' },
  'chakra': { theme: 'spiritualite' },
  'énergie': { theme: 'spiritualite' },
  'énergétique': { theme: 'spiritualite' },
  'bien-être': { theme: 'spiritualite' },
  'bienêtre': { theme: 'spiritualite' },
  'développement personnel': { theme: 'spiritualite' },
  'croissance': { theme: 'spiritualite' },
  'âme': { theme: 'spiritualite' },
  'karma': { theme: 'spiritualite' },
  'retraite': { theme: 'spiritualite' },
  'ashram': { theme: 'spiritualite' },

  // ═══════════════════════════════════════════════════════════
  // INTENTIONS : AMITIÉ
  // ═══════════════════════════════════════════════════════════
  'ami': { intention: 'amitie' },
  'amie': { intention: 'amitie' },
  'amis': { intention: 'amitie' },
  'amies': { intention: 'amitie' },
  'amitié': { intention: 'amitie' },
  'amitiés': { intention: 'amitie' },
  'pote': { intention: 'amitie' },
  'potes': { intention: 'amitie' },
  'copain': { intention: 'amitie' },
  'copine': { intention: 'amitie' },
  'copains': { intention: 'amitie' },
  'copines': { intention: 'amitie' },
  'buddy': { intention: 'amitie' },
  'pal': { intention: 'amitie' },
  'camarade': { intention: 'amitie' },

  // ═══════════════════════════════════════════════════════════
  // INTENTIONS : ROMANCE
  // ═══════════════════════════════════════════════════════════
  'amour': { intention: 'romance' },
  'amoureuse': { intention: 'romance' },
  'amoureux': { intention: 'romance' },
  'romantique': { intention: 'romance' },
  'romance': { intention: 'romance' },
  'relation': { intention: 'romance' },
  'rencontre': { intention: 'romance' },
  'rencontres': { intention: 'romance' },
  'dating': { intention: 'romance' },
  'date': { intention: 'romance' },
  'couple': { intention: 'romance' },
  'partenaire': { intention: 'romance' },
  'âme soeur': { intention: 'romance' },
  'moitié': { intention: 'romance' },
  'séduire': { intention: 'romance' },
  'séduction': { intention: 'romance' },
  'flirt': { intention: 'romance' },
  'flirter': { intention: 'romance' },

  // ═══════════════════════════════════════════════════════════
  // INTENTIONS : PROJET
  // ═══════════════════════════════════════════════════════════
  'projet': { intention: 'projet' },
  'projets': { intention: 'projet' },
  'collaboration': { intention: 'projet' },
  'collaborer': { intention: 'projet' },
  'collaborateur': { intention: 'projet' },
  'créer ensemble': { intention: 'projet' },
  'co-créer': { intention: 'projet' },
  'cocréer': { intention: 'projet' },
  'monter': { intention: 'projet' },
  'lancer': { intention: 'projet' },
  'entreprendre': { intention: 'projet' },
  'associé': { intention: 'projet' },
  'associée': { intention: 'projet' },
  'cofondateur': { intention: 'projet' },
  'partenariat': { intention: 'projet' },
  'business': { intention: 'projet' },
  'freelance': { intention: 'projet' },
  'indépendant': { intention: 'projet' },

  // ═══════════════════════════════════════════════════════════
  // INTENTIONS : DISCUSSIONS
  // ═══════════════════════════════════════════════════════════
  'discuter': { intention: 'discussions' },
  'discussion': { intention: 'discussions' },
  'discussions': { intention: 'discussions' },
  'parler': { intention: 'discussions' },
  'échanger': { intention: 'discussions' },
  'échange': { intention: 'discussions' },
  'échanges': { intention: 'discussions' },
  'partager': { intention: 'discussions' },
  'partage': { intention: 'discussions' },
  'conversation': { intention: 'discussions' },
  'conversations': { intention: 'discussions' },
  'causer': { intention: 'discussions' },
  'papoter': { intention: 'discussions' },
  'bavarder': { intention: 'discussions' },
  'réseauter': { intention: 'discussions' },
  'networking': { intention: 'discussions' },
};

// Villes connues
const CITIES = [
  'paris', 'lyon', 'marseille', 'toulouse', 'nice', 'nantes', 'bordeaux', 'lille',
  'strasbourg', 'rennes', 'montpellier', 'grenoble', 'toulon', 'dijon', 'angers',
  'reims', 'saint-étienne', 'le havre', 'clermont-ferrand', 'amiens',
  'limoges', 'tours', 'metz', 'besançon', 'orléans', 'rouen', 'caen', 'nancy',
  'new york', 'los angeles', 'chicago', 'san francisco', 'boston', 'miami', 'seattle',
  'london', 'londres', 'manchester', 'birmingham', 'edinburgh', 'dublin',
  'berlin', 'munich', 'hambourg', 'francfort', 'cologne',
  'madrid', 'barcelona', 'barcelone', 'valencia', 'séville',
  'rome', 'milan', 'florence', 'venise', 'naples',
  'amsterdam', 'rotterdam', 'bruxelles', 'bruges', 'anvers',
  'lisbonne', 'porto',
  'genève', 'zurich', 'berne',
  'vienne', 'prague', 'budapest', 'varsovie', 'cracovie',
  'stockholm', 'oslo', 'copenhague', 'helsinki',
  'tokyo', 'kyoto', 'osaka', 'seoul', 'singapour', 'hong kong', 'bangkok', 'bali',
  'sydney', 'melbourne', 'auckland',
  'montreal', 'toronto', 'vancouver', 'quebec',
  'dubai', 'tel aviv', 'le caire', 'casablanca', 'marrakech',
  'rio', 'sao paulo', 'buenos aires', 'mexico', 'bogota', 'lima',
  'cape town', 'johannesburg', 'nairobi',
];

// Mots vides à ignorer
const STOP_WORDS = [
  'je', 'tu', 'il', 'elle', 'on', 'nous', 'vous', 'ils', 'elles',
  'un', 'une', 'le', 'la', 'les', 'des', 'du', 'de', 'à', 'au', 'aux',
  'et', 'ou', 'mais', 'donc', 'car', 'ni', 'que', 'qui', 'quoi', 'dont',
  'ce', 'cette', 'ces', 'mon', 'ma', 'mes', 'ton', 'ta', 'tes',
  'son', 'sa', 'ses', 'notre', 'votre', 'leur', 'leurs',
  'pour', 'avec', 'sans', 'dans', 'sur', 'sous', 'par', 'entre', 'vers',
  'chez', 'contre', 'depuis', 'pendant', 'avant', 'après',
  'être', 'avoir', 'faire', 'aller', 'pouvoir', 'vouloir', 'devoir', 'savoir',
  'suis', 'es', 'est', 'sommes', 'êtes', 'sont',
  'ai', 'as', 'avons', 'avez', 'ont',
  'fais', 'fait', 'faisons', 'faites', 'font',
  'vais', 'vas', 'va', 'allons', 'allez', 'vont',
  'aime', 'aimes', 'aimons', 'aimez', 'aiment',
  'cherche', 'cherches', 'cherchons', 'cherchez', 'cherchent',
  'recherche', 'recherches', 'recherchons', 'recherchez', 'recherchent',
  'veux', 'veut', 'voulons', 'voulez', 'veulent',
  'quelqu', 'quelque', 'quelquun', 'quelques', 'personne', 'gens',
  'très', 'bien', 'bon', 'bonne', 'bons', 'bonnes',
  'beau', 'belle', 'beaux', 'belles',
  'grand', 'grande', 'grands', 'grandes',
  'petit', 'petite', 'petits', 'petites',
  'aussi', 'plus', 'moins', 'tout', 'tous', 'toute', 'toutes',
  'autre', 'autres', 'même', 'mêmes',
  'ici', 'là', 'où', 'quand', 'comment', 'pourquoi',
  'oui', 'non', 'peut', 'peuvent', 'doit', 'doivent',
  'comme', 'si', 'alors', 'encore', 'toujours', 'jamais',
  'vraiment', 'surtout', 'beaucoup', 'peu', 'trop', 'assez',
];

export interface ExtractedKeywords {
  themes: string[];
  intentions: string[];
  city: string | null;
}

export function extractKeywords(text: string): ExtractedKeywords {
  const normalized = text.toLowerCase().trim();
  const words = normalized.split(/[\s,;.!?']+/).filter(w => w.length > 2);

  const themes = new Set<string>();
  const intentions = new Set<string>();
  let city: string | null = null;

  // Chercher ville (expressions de plusieurs mots d'abord)
  for (const c of CITIES) {
    if (normalized.includes(c)) {
      city = c.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
      break;
    }
  }

  // Chercher mots-clés simples
  for (const word of words) {
    if (STOP_WORDS.includes(word)) continue;

    const match = KEYWORD_MAP[word];
    if (match) {
      if (match.theme) themes.add(match.theme);
      if (match.intention) intentions.add(match.intention);
    }
  }

  // Chercher expressions de 2-3 mots
  for (let i = 0; i < words.length - 1; i++) {
    const twoWords = `${words[i]} ${words[i + 1]}`;
    const match2 = KEYWORD_MAP[twoWords];
    if (match2) {
      if (match2.theme) themes.add(match2.theme);
      if (match2.intention) intentions.add(match2.intention);
    }

    if (i < words.length - 2) {
      const threeWords = `${words[i]} ${words[i + 1]} ${words[i + 2]}`;
      const match3 = KEYWORD_MAP[threeWords];
      if (match3) {
        if (match3.theme) themes.add(match3.theme);
        if (match3.intention) intentions.add(match3.intention);
      }
    }
  }

  return {
    themes: Array.from(themes),
    intentions: Array.from(intentions),
    city,
  };
}

// Labels pour affichage
export const THEME_LABELS: Record<string, string> = {
  'musique': '🎵 Musique',
  'art': '🎨 Art',
  'photo': '📷 Photo',
  'cinema': '🎬 Cinéma',
  'litterature': '📚 Littérature',
  'science': '🔬 Science/Tech',
  'politique': '🏛️ Politique',
  'philosophie': '🤔 Philosophie',
  'voyage': '✈️ Voyage',
  'sport': '⚽ Sport',
  'cuisine': '🍳 Cuisine',
  'ecologie': '🌱 Écologie',
  'jeux': '🎮 Jeux',
  'spiritualite': '✨ Spiritualité',
};

export const INTENTION_LABELS_EXTRACTED: Record<string, string> = {
  'amitie': '👋 Amitié',
  'romance': '❤️ Romance',
  'projet': '🚀 Projet',
  'discussions': '💬 Discussions',
};
